module.exports = {
  knowledgeSideBar: {
    前端知识: ['knowledge/introduction'],
    操作系统: ['knowledge/system/process-and-thread'],
    浏览器: ['knowledge/browser/browser-process-and-thread'],
    JavaScript: [
      'knowledge/js/null-and-undefined',
      'knowledge/js/types-and-conversion',
      'knowledge/js/js-array',
      'knowledge/js/handwritten-code',
    ],
    数据结构: [
      'knowledge/data-structure/stack',
      'knowledge/data-structure/queue',
      'knowledge/data-structure/deque',
      'knowledge/data-structure/linked-list',
      'knowledge/data-structure/set',
      'knowledge/data-structure/dictionary-and-hashtable',
      'knowledge/data-structure/tree',
      'knowledge/data-structure/binary-heap',
      'knowledge/data-structure/graph',
    ],
    算法: [
      'knowledge/algorithms/euclidean',
      'knowledge/algorithms/recursion',
      'knowledge/algorithms/sorting',
      'knowledge/algorithms/search',
      'knowledge/algorithms/randomized',
      'knowledge/algorithms/divide-and-conquer',
      'knowledge/algorithms/dp',
      'knowledge/algorithms/greedy',
      'knowledge/algorithms/backtracking',
      'knowledge/algorithms/algorithmic-complexity',
    ],
  },
};
